### ISSUE TITLE
ActivityEditor: InstantiationException

### ISSUE THREAD

**Issue by bosik** [bosik/diacomp#129]
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
  at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4378)
  at android.app.ActivityThread.access$1000(ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5910)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
**Caused by: android.app.Fragment$InstantiationException:** 
  at android.app.Fragment.instantiate(Fragment.java:638)
  at android.app.FragmentState.instantiate(Fragment.java:111)
  at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1791)
  at android.app.Activity.onCreate(Activity.java:982)
  **at org.bosik.diacomp.android.frontend.activities.ActivityEditor.onCreate(ActivityEditor.java:49)**
  **at org.bosik.diacomp.android.frontend.activities.ActivityEditorTime.onCreate(ActivityEditorTime.java:42)
  at android.app.Activity.performCreate(Activity.java:6178)**
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

**Comment by bosik** [comment]
Seems fixed within 54f1534290ffa76ef287c9d6b20f0aa1b039d286
